[package]
name = "fastasx"
version = "0.1.0"
edition = "2021"
authors = ["Luke Thompson <luke-a-thompson@outlook.com>"]

[dependencies]
byteorder = "1.5.0"
ringbuf = "0.4.1"

[build]
rustflags = ["-C", "target-cpu=native"]
